## Scoped Role for managing Secrets (private key storage) within this namespace only.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubevalet.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubevalet.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "list", "watch", "delete"]
