apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubevalet.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubevalet.labels" . | nindent 4 }}
